### ISSUE TITLE
Not downloaded 

### ISSUE THREAD

**Issue by bethcbl** [bulkdataio/bulkdata#1]
Good Afternoon,

We have tried purchasing data from yourself this morning however it is still showing as processing 90 minutes later and we haven’t had any emails. I am worried we have used the incorrect email address? The money has left our account.

Can you help please?

Thanks

Beth 

![image](https://user-images.githubusercontent.com/126081453/220631353-63b1c2b2-ef28-4d57-a900-6b74d10b5fc6.png)

![image](https://user-images.githubusercontent.com/126081453/220631366-489e24ac-ae47-4186-bf36-2a5767027b5a.png)

**Comment by bulkdataio** [comment]
Hello Beth,
I apologize for the delay in providing you with the download link. There was a technical issue that caused this which should be fixed now. If you still have any questions or concerns, please don’t hesitate to contact us using email hello@bulkdata.io. We are here to help.

Regards,
Zakk
